version: "3"

services:
    db:
        container_name: bankoss-db
        image: mysql:8.0.27
        environment:
            MYSQL_DATABASE: bankoss
            MYSQL_USER: bankoss
            MYSQL_PASSWORD: bankoss
            MYSQL_ROOT_PASSWORD: mysql
        command:
            - --default-authentication-plugin=mysql_native_password
        volumes:
            - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
#            - ./data:/var/lib/mysql
        ports:
            -   "3306:3306"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: housekeeping-book-app
        image: openjdk:11-jdk
        ports:
            -   "8080:8080"
        volumes:
            -   ./:/app
        working_dir: /app
        command: "java -jar -Dspring.profiles.active=local build/libs/bankoss-0.0.1-SNAPSHOT.jar"
        depends_on:
            -   db
        restart: always

